// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpwigxodkbgshuytxvrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxwd2lneG9ka2Jnc2h1eXR4dnJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTgwNjYsImV4cCI6MjA2Mjk5NDA2Nn0.1-nBVlRtknzR45Q8EeuXsZdr_uYcEgCHjrKonvrOt78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);